# Start from the base Airflow image
FROM apache/airflow:2.9.3

# Switch to root user to install packages
USER root

# Update package list and install Java and procps
RUN apt-get update
RUN apt install -y default-jdk
RUN apt-get autoremove -yqq --purge
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-arm64

# Switch to airflow user
USER airflow

# Copy the requirements.txt file into the Docker image
COPY requirements.txt /requirements.txt

# Install Python packages from requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
